[Compute AG] Agentless Secret Detection
PaloAltoNetworks/prisma-cloud-docs pull request #1584
Opened 2023-10-05 21:11 UTC by rcaballeromx

2023-10-05 21:58 UTC, omri86 requested changes
LGTM good job @rcaballeromx thanks for the quick turnaround!

2023-10-05 21:58 UTC, omri86 commented on compute/admin_guide/compliance/detect_secrets.adoc
> +=== Defender Secret Detection
Secret -> Secrets

2023-10-05 21:58 UTC, omri86 commented on compute/admin_guide/compliance/detect_secrets.adoc
> +Select *Monitor > Compliance > Compliance Explorer* and filter the results using the `secrets` keyword to see the impacted images and containers.
filtering with "secrets" won't give the the relevant checks, a proper way to look would be to search for the relevant checks you listed below by IDs

2023-10-05 21:58 UTC, omri86 commented on compute/admin_guide/compliance/detect_secrets.adoc
> +=== Agentless Secret Detection
Secret -> Secrets

2023-10-05 21:58 UTC, omri86 commented on compute/admin_guide/compliance/detect_secrets.adoc
> +Select *Monitor > Compliance > Compliance Explorer* and filter the results using `secret` as a keyword to see the impacted hosts.
filter using the ID

2023-10-05 21:58 UTC, omri86 commented on compute/admin_guide/compliance/detect_secrets.adoc
> +Select *Monitor > Compliance > Compliance Explorer* and filter the results using `secret` as a keyword to see the impacted container images.
filter using the ID

2023-10-05 21:58 UTC, omri86 commented on compute/admin_guide/compliance/detect_secrets.adoc
> +* The private keys of encryption keys
Private encryption keys

2023-10-05 21:58 UTC, omri86 commented on compute/admin_guide/compliance/detect_secrets.adoc
> +* A redacted snippet of the secret with a length of less than 10 characters.
* A redacted snippet of the secret with a length of less than 10 characters.
    * 10% visible characters for secrets above 30 characters up to a maximum of 10 characters.
    * Maximum of 3 visible characters for secrets under 30 characters.

2023-10-05 21:58 UTC, omri86 commented on compute/admin_guide/compliance/detect_secrets.adoc
> +* The filename where the secret was detected.
The path to the file where the secret was detected.

2023-10-05 21:58 UTC, omri86 commented on compute/admin_guide/compliance/detect_secrets.adoc
> +* The line where the secret was detected.
The line and offset in the file where the secret was detected in the form of `line:offset`.

2023-10-05 21:58 UTC, omri86 commented on compute/admin_guide/compliance/detect_secrets.adoc
> +* The offset in the line where the secret was detected.
remove considering my previous comment

2023-10-05 21:58 UTC, omri86 commented on compute/admin_guide/compliance/detect_secrets.adoc
> +When agentless scanning detects a secret in a host or container image, only the following information is sent to the Prisma Cloud console.
this is missing:
* The secret type (see list below) <- maybe link this to the relevant section that lists the types
* The modified time of the file where the secret was detected.

2023-10-05 21:58 UTC, omri86 commented on compute/admin_guide/compliance/detect_secrets.adoc
> +Agentless scanning detects the following secrets.
following secrets -> following secrets types

2023-10-05 21:58 UTC, omri86 commented on compute/admin_guide/compliance/detect_secrets.adoc
> +Agentless scanning detects sensitive information inside your hosts and container images.
Agentless scanning detects sensitive information inside files in your hosts and container images filesystem.

2023-10-06 02:49 UTC, rcaballeromx commented
@omri86 I addressed all your feedback. Thank you for the quick review.
@Pubs-MV I've tested the content and it's ready to be merged.

2023-10-06 16:45 UTC, merged