Update wildfire.adoc
PaloAltoNetworks/prisma-cloud-docs pull request #386
Opened 2022-06-27 20:31 UTC by Pubs-MV

Changes to clarify that for container/CI scanning, only executable files that were not installed with a package manager are checked with wildfire.

2022-06-27 21:05 UTC, Pubs-MV commented
changes for PCSUP-9395

2022-06-30 11:32 UTC, omri86 requested changes
Please see my comments below and ping in the issue when fixed

2022-06-30 11:32 UTC, omri86 commented on compute/admin_guide/configure/wildfire.adoc
> +** Objects that are not shared. Shared objects are not scanned by WildFire.
the changes to this line does not make sense, please leave as is

2022-06-30 11:32 UTC, omri86 commented on compute/admin_guide/vulnerability_management/malware_scanning.adoc
> +See xref:../configure/custom_feeds.adoc#malware-signatures[Import custom malware data], for information on how to upload custom malware data to Console and use it for image scanning.
Allow me to suggest the following phrasing - and please be sure to fix the links as I mentioned in the text:



Malware data used for analysis is originating from three possible locations and flows:
1. Intelligence Stream (add link to IS page)
2. Wildfire service (add link to WF page) - note that WildFire is used only for runtime protection for hosts and containers and when scanning in CI. When scanning using a Defender the malware MD5 can be used for malware detection.
3. Custom feeds - see Import custom malware data (add link to malware sigs), for information on how to upload custom malware data to Console and use it for image scanning.

2022-06-30 11:44 UTC, markvai commented on compute/admin_guide/configure/wildfire.adoc
> +** Objects that are not shared. Shared objects are not scanned by WildFire.
+1 That it is not clear.

But we need to add a bullet for CI scanning, suggest something like:
- During CI scanning, only executable files that were not written as part of a package installation will be analyzed by WildFire.

2022-06-30 11:47 UTC, markvai commented on compute/admin_guide/vulnerability_management/malware_scanning.adoc
> +The image scanner looks for malware in binaries in the image layers, including the base layer. When Prisma Cloud detects malware in an image, it logs the vulnerability in the image scan report.
Actually it's not exactly a vulnerability, when it finds malware it is reported as a compliance issue.

2022-06-30 12:03 UTC, markvai commented on compute/admin_guide/vulnerability_management/malware_scanning.adoc
> +See xref:../configure/custom_feeds.adoc#malware-signatures[Import custom malware data], for information on how to upload custom malware data to Console and use it for image scanning.
+1 On the general structure Omri suggested.

However, @omri86 I am not sure we should mention runtime in this context as this page describes malware detection in the context of image scanning.

Suggest to modify a bit and explain what is done in each technique.

Malware detection is based on the following techniques:

- Intelligence Stream (add link to IS page) - Prisma Cloud searches the malicious feed for the executable's hash.
- Custom feeds - see Import custom malware data (add link to malware sigs), for information on how to upload custom malware data to Console and use it for image scanning.
Prisma Cloud searches the custom feed for the executable's hash.
- Wildfire service (add link to WF page) - WildFire service is queried with the executable's hash, if not found and upload is enabled, the file is also uploaded for analysis.
NOTE: WildFire is only supported for image scanning when used in CI.

2022-06-30 12:10 UTC, omri86 commented on compute/admin_guide/vulnerability_management/malware_scanning.adoc
> +See xref:../configure/custom_feeds.adoc#malware-signatures[Import custom malware data], for information on how to upload custom malware data to Console and use it for image scanning.
@markvai if runtime was not part of the customer issue which triggered these changes then I agree, we can drop that part

2022-07-08 20:59 UTC, Pubs-MV commented on compute/admin_guide/configure/wildfire.adoc
> +** Objects that are not shared. Shared objects are not scanned by WildFire.
done, please review

2022-07-08 21:18 UTC, Pubs-MV commented on compute/admin_guide/vulnerability_management/malware_scanning.adoc
> +See xref:../configure/custom_feeds.adoc#malware-signatures[Import custom malware data], for information on how to upload custom malware data to Console and use it for image scanning.
done, please review

2022-07-08 21:21 UTC, merged