Mor shabi pan gke arm
PaloAltoNetworks/prisma-cloud-docs pull request #498
Opened 2022-08-14 15:48 UTC by MorShabiPAN

Hi @rcaballeromx,

I couldn't make all the changes in your branch so I tried to copy the files and link changes to here and make my adjustments.

Can you please review, and share your thoughts?

Best,
Mor

This PR is following PR #476

2022-08-15 12:58 UTC, sgordon46 commented on compute/admin_guide/install/fragments/install_defender_twistcli_export_kubectl.adoc
> +You can also use the `twistcli` command-line utility to generate the Defender `DaemonSet` YAML configuration files. Deploy the cusjtom resources with `kubectl` following this procedure.
cusjtom is mispelled.

2022-08-17 00:03 UTC, rcaballeromx commented
Please review #476 instead. This content doesn't build properly.

2022-08-17 00:04 UTC, rcaballeromx requested changes
Please review #476 and ensure all the needed changes are included there. This PR doesn't build properly.

2022-08-17 00:05 UTC, rcaballeromx commented
I added all the changes to the content present in this PR to #476. Please let me know if I missed any changes.

2022-08-19 16:49 UTC, Pubs-MV commented
@rcaballeromx added all the changes to the content present in this PR to https://github.com/PaloAltoNetworks/prisma-cloud-docs/pull/476.

2022-08-19 16:49 UTC, closed without merging