ReplacedTwistlockInstances
PaloAltoNetworks/prisma-cloud-docs pull request #50
Opened 2021-10-19 03:57 UTC by ssugandh

Please review the "Twistlock" instances that I replaced with "Prisma Cloud Compute".

2021-10-26 02:05 UTC, iansk requested changes

2021-10-26 02:05 UTC, iansk commented on api/descriptions/settings/secrets_post.md
> +      "appID": "Prisma Cloud Compute_Console",
@ssugandh Not sure if spaces are acceptable here. Change to all underscores

2021-10-26 06:59 UTC, ssugandh commented on api/descriptions/settings/secrets_post.md
> +      "appID": "Prisma Cloud Compute_Console",
@iansk I added the underscore. Please see my latest commit.

2021-10-27 02:25 UTC, iansk commented on api/descriptions/settings/secrets_post.md
> +      "appID": "Prisma Cloud Compute_Console",
@ssugandh You also need to update the value in the example curl request.

2021-10-27 14:48 UTC, iansk approved these changes

2021-10-27 14:49 UTC, merged

2021-10-27 14:50 UTC, iansk commented
Nice job, @ssugandh. I've just merged your first PR!