adding all the azure AD OIDC based configuration missing steps and details
PaloAltoNetworks/prisma-cloud-docs pull request #581
Opened 2022-10-12 17:40 UTC by priteshchandaliya

2022-10-12 21:38 UTC, rcaballeromx commented on compute/admin_guide/authentication/oidc.adoc
> +. Add above group claim and select the *Groups assigned to the application* option.
@priteshchandaliya The steps above do not mention any groups, they are mentioned below. Do we need to add this step or should the step that follows needs to be modified?

2022-10-13 21:17 UTC, rcaballeromx commented
@Pubs-MV The PR is ready for merging.

2022-10-13 22:34 UTC, pfox1969 requested changes
I don't think we need the image::oidc_client_secret.png in there. Because you can only copy the client secret's value at the time of creation. That screen cap is after the creation.

2022-10-13 22:38 UTC, pfox1969 approved these changes

2022-10-13 22:53 UTC, rcaballeromx approved these changes
Thank you @pfox1969 for your changes.
I removed the screenshot as requested too.
@Pubs-MV I verified that the content builds.

2022-10-14 18:29 UTC, merged

2022-10-14 18:31 UTC, Pubs-MV commented
also related to PCSUP-10521