Update oam.adoc
PaloAltoNetworks/prisma-cloud-docs pull request #63
Opened 2021-10-25 17:45 UTC by jodydadescott

2021-10-25 17:45 UTC, jodydadescott commented
Updates for oam ping

2022-01-21 04:51 UTC, iansk commented
@rcaballeromx Can you please review these changes and let me know if they're ok to merge as-is?

2022-01-21 18:30 UTC, rcaballeromx requested changes
Thank you for your contribution!
I've left some suggestions to make the text clearer and easier to read.  PTAL

It would be great if you could add a sentence at the beginning of the example letting readers know what is the goal of the example. Why should they try to run the commands? When would they need to consider doing it?

2022-01-21 18:30 UTC, rcaballeromx commented on cns/saas/admin_guide/apoctl/oam.adoc
> +The `+ping+` command is used for network connectivity troubleshooting. Running the command will cause the specified processing unit to initiate a flow towards the specified destination IP and port. A
```suggestion
Use the `+ping+` command to troubleshoot network connectivity. The command starts a flow from the specified processing unit to the destination IP and port. A successful ping returns the status code `+0+`, and writes a report to `+stdout+`. An unsuccessful ping returns the status code `+1+`, and writes a report the errors to `+stderr+`. The reports contain information about the source and destination. How the command and reports operate depends on whether the destination is a processing unit.
```

2022-01-21 18:30 UTC, rcaballeromx commented on cns/saas/admin_guide/apoctl/oam.adoc
> +If the destination is not a processing unit then the destination must be listening on the specified port for a successful response. The connection will be set up and then immediately dropped. The rep
```suggestion
A destination that is not a processing unit must listen to the specified port for a successful response. The connection is immediately set up and then dropped. The report includes detailed information about the source, but only the IP and port of such a destination.
```

2022-01-21 18:30 UTC, rcaballeromx commented on cns/saas/admin_guide/apoctl/oam.adoc
> +If the destination is a processing unit then the destination enforcer will handle the flow. Hence it is not necessary for the destination to be actively listening to the destination port. Even if it
```suggestion
A destination that is a processing unit has an enforcer that handles the flow, and the destination doesn't have to actively listen to the port. If it is listening on the port the enforcer still consumes the flow. The report includes detailed information about both the source and destination.
```

2022-01-21 18:30 UTC, rcaballeromx commented on cns/saas/admin_guide/apoctl/oam.adoc
> + Consider the situation where there are two processing units and the admin suspects that there may be a network device within the path that is blocking traffic on port 9000. The admin knows that SSH
```suggestion
 Consider the following scenario: You have two processing units and you suspect that a network device within the path connecting them is blocking traffic on port 9000. You knows that SSH on port 22 works and run the following command:
```

2022-01-21 18:30 UTC, rcaballeromx commented on cns/saas/admin_guide/apoctl/oam.adoc
> + The command is successful so they run the command
```suggestion
 The command succeeds, and you run the following command:
```

2022-01-21 18:30 UTC, rcaballeromx commented on cns/saas/admin_guide/apoctl/oam.adoc
> + The command fails. Now the admin knows the problem is with the network.
```suggestion
 Because the command fails, you now know that the problem is with the network.
```

2022-03-14 21:51 UTC, Pubs-MV commented
Made these changes using PR#232

2022-03-14 21:51 UTC, closed without merging