Update api.adoc
PaloAltoNetworks/prisma-cloud-docs pull request #64
Opened 2021-10-25 18:09 UTC by jodydadescott

2022-01-21 04:51 UTC, iansk commented
@rcaballeromx Can you please review these changes and let me know if they're ok to merge as-is?

2022-01-21 18:32 UTC, rcaballeromx requested changes
Nothing major, just some typos and grammar fixes.

2022-01-21 18:32 UTC, rcaballeromx commented on cns/saas/admin_guide/apoctl/api.adoc
> +exported using the `+export+` subcommand. Note that when importing
```suggestion
exported using the `+export+` subcommand. When importing
```

2022-01-21 18:32 UTC, rcaballeromx commented on cns/saas/admin_guide/apoctl/api.adoc
> +the label will be used to determine whether to overwrite the existing
```suggestion
the label is used to determine whether to overwrite the existing
```

2022-01-21 18:32 UTC, rcaballeromx commented on cns/saas/admin_guide/apoctl/api.adoc
> +remain consistient it may result in the undesired duplication of
```suggestion
remain consistent, it may result in the undesired duplication of 
```

2022-01-21 18:32 UTC, rcaballeromx commented on cns/saas/admin_guide/apoctl/api.adoc
> +configuration.
```suggestion
the configuration.
```

2022-03-14 21:33 UTC, Pubs-MV commented
Thank you, @jodydadescott your changes are included in PR #231

2022-03-14 21:33 UTC, closed without merging