Update scan_acr.adoc
PaloAltoNetworks/prisma-cloud-docs pull request #643
Opened 2022-11-11 15:52 UTC by timberbee

The current version says to use credentials from the pull down menu, however you cannot you Prisma Cloud credentials to authenticate to an Azure Container Registry. This is explained in the authentication section but if you come straight to how to configure your registry you will not get that information. Instead you will get frustrated.

2022-12-05 21:43 UTC, Pubs-MV commented
please review this for 22.12.

Also, let Ian know if the same changes are applicable for 22.06.

2022-12-14 16:04 UTC, rcaballeromx requested changes
Please accept the suggestion to apply the needed changes.

2022-12-14 16:04 UTC, rcaballeromx commented on compute/admin_guide/vulnerability_management/registry_scanning/scan_acr.adoc
> +You need to create a Service Principal with Reader Role and scoped for the subscription in order to scan the registry. You cannot use the Cloud Accounts added to Prisma Cloud even though they have th
Thank you @timberbee I've edited the text and fixed the link's syntax. 
```suggestion
To scan the registry, you need a service principal in Azure with the `Reader` role and scoped for your subscription. The Azure account you added to Prisma Cloud can't perform the scans even if they have the correct permissions. For more information see xref:../authentication/credentials-store[credentials store]
```

2022-12-14 16:06 UTC, rcaballeromx commented
@Pubs-MV I think this also applies to 22.06. @timberbee Can you confirm?

2023-02-10 04:26 UTC, Pubs-MV commented
@rcaballeromx can you please review and confirm if these changes are required/worked into our content for lagrange so we can  close this PR with the link to what is done.

2023-03-08 21:23 UTC, closed without merging