Update auth.adoc
PaloAltoNetworks/prisma-cloud-docs pull request #65
Opened 2021-10-25 18:23 UTC by jodydadescott

Add pc-token sub command documentation

2022-01-21 04:51 UTC, iansk commented
@rcaballeromx Can you please review these changes and let me know if they're ok to merge as-is?

2022-01-21 18:34 UTC, rcaballeromx requested changes
Missing a pronoun for clarity.

2022-01-21 18:34 UTC, rcaballeromx commented on cns/saas/admin_guide/apoctl/auth.adoc
> +The `+pc-token+` subcommand allows to retrieve a Microsegmentation token using Prisma
```suggestion
The `+pc-token+` subcommand allows you to retrieve a microsegmentation token using Prisma
```

2022-01-21 18:34 UTC, rcaballeromx commented on cns/saas/admin_guide/apoctl/auth.adoc
> + apoctl auth pc-token --token "$TOKEN"
@iansk The examples on this page do not have markup making them code blocks. Is that intentional?

2022-03-14 19:10 UTC, Pubs-MV commented
closing this request as the changes from PR #168 and #65 are in #230

2022-03-14 19:10 UTC, closed without merging